# Autogenerated wrapper script for wfdb_wrapper_jll for aarch64-linux-musl
export read_ann, read_header, read_samples

JLLWrappers.@generate_wrapper_header("wfdb_wrapper")
JLLWrappers.@declare_executable_product(read_ann)
JLLWrappers.@declare_executable_product(read_header)
JLLWrappers.@declare_executable_product(read_samples)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        read_ann,
        "bin/read_ann",
    )

    JLLWrappers.@init_executable_product(
        read_header,
        "bin/read_header",
    )

    JLLWrappers.@init_executable_product(
        read_samples,
        "bin/read_samples",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
